version: '3'

services:

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=P@ssw0rd!
      - DB_DB=postgres
    depends_on:
      - db

  flyway:
    build: ./migrations
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=P@ssw0rd! migrate
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"
